version: '3.0'
services:
  spring-jar:
    image: openjdk:8-jdk-alpine
    container_name: spring-jar
    volumes:
      - ./target/demo-0.0.1.jar:/app.jar
    environment:
      - TZ="Asia/Shanghai"
    ports:
      - 8080:8080
    links:
      - spring-mysql
    restart: always
    entrypoint: java -jar /app.jar

  spring-nginx:
    image: nginx:1.17.0
    container_name: spring-nginx # 容器名
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, "-g", "daemon off;"]
    links:
      - spring-jar
    restart: always

  spring-mysql:
    image: mysql:5.7
    container_name: spring-mysql
    volumes:
      - ./docker/data/mysql/:/var/lib/mysql
      - ./docker/mysql/database/bookshop.sql:/docker-entrypoint-initdb.d/bookshop.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3307:3306
    restart: always