spring:

  datasource:
    url: jdbc:mysql://spring-mysql:3306/bookshop?serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTLM5
    servlet:
      content-type: text/html

  devtools:
    restart:
      additional-paths: src/main/kotlin
      enabled: true
